### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by scpchicken** [scpchicken/assembly-for-noobs#1]
- [ ] add flags
- [ ] add user defined function with rbp & rsp var referencing
- [ ] show effective ops (real code) for func syntactical sugar (probably too advanced)
- [ ] add repne scasb (we'll see)
- [ ] lea mul trick
- [x] fix jump cond things
